# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Stark"
license = "MIT"
licenselink = "https://github.com/nikovacevic/stark/blob/master/LICENSE.md"
description = "Stark, minimal theme"
homepage = "https://stark.nikovacevic.io/"
tags = ["minimal", "blog", "stark", "white"]
features = ["", ""]
min_version = 0.15

[author]
  name = "Niko Kovacevic"
  homepage = "https://nikovacevic.io/"
